
import java.math.BigDecimal;
import java.sql.*;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Microdata
 */
public class SignupForm2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignupForm2.class.getName());

    /**
     * Creates new form SignupForm2
     */
    public SignupForm2(String accNum, String username, String firstname, String lastname, String mobile) {
        initComponents();
    
        lblAcc.setText(accNum);
        lblUser.setText(username);
        lblFN.setText(firstname);
        lblLN.setText(lastname);
        lblMobile.setText(mobile);

        generateWallets();
    }
    
    public Connection getConnection() {
    try {
        Class.forName("com.mysql.jdbc.Driver");
        return DriverManager.getConnection("jdbc:mysql://localhost:3306/jcappdb", "root", "");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Database connection failed: " + e.getMessage());
        return null;
        }
    }
    
    public void generateWallets() {
        //lblBTCadd.setText(generateRandomWallet());
        //lblETHadd.setText(generateRandomWallet());
        //lblUSDCadd.setText(generateRandomWallet());
        try (Connection conn = getConnection()) {
            
            String btc = generateUniqueWallet(conn, "BTC", "BTCaddress");
            String eth = generateUniqueWallet(conn, "ETH", "ETHaddress");
            String usdc = generateUniqueWallet(conn, "USDC", "USDCaddress");


            lblBTCadd.setText(btc);
            lblETHadd.setText(eth);
            lblUSDCadd.setText(usdc);
            
            
            String btcAddress = lblBTCadd.getText();
            String ethAddress = lblETHadd.getText();
            String usdcAddress = lblUSDCadd.getText();
            String accNumber = lblAcc.getText(); 
            
           
            PreparedStatement pstBTC = conn.prepareStatement("INSERT INTO BTC (account_number, BTCaddress, amount) VALUES (?, ?, ?)");
            pstBTC.setString(1, accNumber);
            pstBTC.setString(2, btcAddress);
            pstBTC.setBigDecimal(3, new BigDecimal("0.0"));
            pstBTC.executeUpdate();

  
            PreparedStatement pstETH = conn.prepareStatement("INSERT INTO ETH (account_number, ETHaddress, amount) VALUES (?, ?, ?)");
            pstETH.setString(1, accNumber);
            pstETH.setString(2, ethAddress);
            pstETH.setBigDecimal(3, new BigDecimal("0.0"));
            pstETH.executeUpdate();

            
            PreparedStatement pstUSDC = conn.prepareStatement("INSERT INTO USDC (account_number, USDCaddress, amount) VALUES (?, ?, ?)");
            pstUSDC.setString(1, accNumber);
            pstUSDC.setString(2, usdcAddress);
            pstUSDC.setBigDecimal(3, new BigDecimal("0.0"));
            pstUSDC.executeUpdate();

            JOptionPane.showMessageDialog(null, "Wallets created and stored successfully!");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error saving wallets: " + e.getMessage());
            }
    }

    public String generateRandomWallet() {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder wallet = new StringBuilder();
        Random rand = new Random();

        for (int i = 0; i < 7; i++) {
            wallet.append(chars.charAt(rand.nextInt(chars.length())));
        }
        return wallet.toString();
       }
    
    public String generateUniqueWallet(Connection conn, String tableName, String columnName) throws SQLException {
        
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        Random rand = new Random();
        String wallet;
        boolean exists;

        do {
            
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 7; i++) {
                sb.append(chars.charAt(rand.nextInt(chars.length())));
            }
            wallet = sb.toString();

            String query = "SELECT COUNT(*) FROM " + tableName + " WHERE " + columnName + " = ?";
            try (PreparedStatement pst = conn.prepareStatement(query)) {
                pst.setString(1, wallet);
                ResultSet rs = pst.executeQuery();
                rs.next();
                exists = rs.getInt(1) > 0;
            }
        } while (exists);

        return wallet;
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFN = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblLN = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblAcc = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBTCadd = new javax.swing.JLabel();
        lblETHadd = new javax.swing.JLabel();
        lblUSDCadd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("  Take note of your details.");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First name:");

        lblFN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFN.setForeground(new java.awt.Color(255, 255, 255));
        lblFN.setText("Username");

        lblMobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMobile.setForeground(new java.awt.Color(255, 255, 255));
        lblMobile.setText("Username");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile number:");

        lblLN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLN.setForeground(new java.awt.Color(255, 255, 255));
        lblLN.setText("Username");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last name:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer ID:");

        lblAcc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAcc.setForeground(new java.awt.Color(255, 255, 255));
        lblAcc.setText("Username");

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(0, 0, 0));
        btnNext.setText("Back to Login");
        btnNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BTC address:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ETH address:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USDC address:");

        lblBTCadd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBTCadd.setForeground(new java.awt.Color(255, 255, 255));
        lblBTCadd.setText("Username");

        lblETHadd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblETHadd.setForeground(new java.awt.Color(255, 255, 255));
        lblETHadd.setText("Username");

        lblUSDCadd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUSDCadd.setForeground(new java.awt.Color(255, 255, 255));
        lblUSDCadd.setText("Username");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLN)
                            .addComponent(lblFN)
                            .addComponent(lblUser)
                            .addComponent(lblAcc)
                            .addComponent(lblMobile, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(86, 86, 86)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBTCadd)
                            .addComponent(lblETHadd)
                            .addComponent(lblUSDCadd))
                        .addGap(124, 124, 124))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUser)
                    .addComponent(jLabel3)
                    .addComponent(lblBTCadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFN)
                    .addComponent(jLabel5)
                    .addComponent(lblETHadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblLN)
                    .addComponent(jLabel6)
                    .addComponent(lblUSDCadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcc)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        WelcomeForm back = new WelcomeForm();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        new SignupForm2("","","","","").setVisible(true); // placeholder values
            });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAcc;
    private javax.swing.JLabel lblBTCadd;
    private javax.swing.JLabel lblETHadd;
    private javax.swing.JLabel lblFN;
    private javax.swing.JLabel lblLN;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblUSDCadd;
    private javax.swing.JLabel lblUser;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
